### ISSUE TITLE
need to add DNAT rule resource for a Nat gateway

### ISSUE THREAD

**Issue by WayneFromHuawei** [terraform-providers/terraform-provider-flexibleengine#108]
there is no DNAT rule resource supported in the provider. please add a resource thanks

**Comment by antonin-a** [comment]
Hello @niuzhenguo , online doc is not updated yey but I think we can find it. @WayneFromHuawei can you send it directly yo Zhenguo ?

**Comment by antonin-a** [comment]
@niuzhenguo , NATG api doc is now up to date : https://docs.prod-cloud-ocb.orange-business.com/en-us/api/nat/en-us_topic_0130808144.html

**Comment by niuzhenguo** [comment]
@antonin-a Thanks for the info, will test the API first, if OK, the DNAT resource will be available soon.

**Comment by niuzhenguo** [comment]
need to address WAF issue first.
