### ISSUE TITLE
CCE flexibleengine_cce_cluster_v3 : cluster_version argument isn't optional

### ISSUE THREAD

**Issue by o-rcharmont** [terraform-providers/terraform-provider-flexibleengine#113]
Hi there,

About the deployment of a CCE cluster (flexibleengine_cce_cluster_v3), cluster_version argument isn't optional as describe in the documentation.
If you don't put it :
error message: {"errorCode":"E.CFE.4000407","reason":"Version is too low","message":"lowest version is v1.7.3-r10"}

### Terraform Version
└─ $ ▶ terraform -v
Terraform v0.11.11
+ provider.flexibleengine v1.4.0

### Affected Resource(s)
flexibleengine_cce_cluster_v3

### Terraform Configuration Files
```hcl
resource "flexibleengine_cce_cluster_v3" "ccecluster1" {
  name = "${var.cce_cluster_name}"
  cluster_type = "${var.cce_cluster_type}"
  #cluster_version = "${var.cce_cluster_version}"
  flavor_id = "${var.cce_cluster_flavorid}"
  vpc_id = "${local.vpc_id}"
  subnet_id = "${local.subnet1a_id}"
  container_network_type = "${var.cce_container_network_type}"
  description = "${var.cce_description}"
}
```

### Debug Output
```hcl
Error: Error applying plan:

1 error(s) occurred:

2019-01-29T17:21:34.244+0100 [DEBUG] plugin.terraform-provider-flexibleengine_v1.4.0_x4: 2019/01/29 17:21:34 [ERR] plugin: plugin server: accept unix /tmp/plugin807992753: use of closed network connection
* flexibleengine_cce_cluster_v3.ccecluster1: 1 error(s) occurred:

* flexibleengine_cce_cluster_v3.ccecluster1: Error creating flexibleengine Cluster: Bad request with: [POST https://cce.eu-west-0.prod-cloud-ocb.orange-business.com/api/v3/projects/a9b00e7dc984480d9e61ed2a70dff8f3/clusters], error message: {"errorCode":"E.CFE.4000407","reason":"Version is too low","message":"lowest version is v1.7.3-r10"}
```

### Expected Behavior
Without the argument cluster_version, cce cluster is created with the last supported cce version

### Actual Behavior
Without the argument cluster_version, cce cluster isn't created because of the default version used ({"errorCode":"E.CFE.4000407","reason":"Version is too low","message":"lowest version is v1.7.3-r10"})

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
n/a

### References
n/a

**Comment by niuzhenguo** [comment]
@o-rcharmont Thanks for raising this, seems something wrong with the online API docs on Orange Cloud, which said the version is option but we got errors, will dig more.

**Comment by niuzhenguo** [comment]
I will temporarily give it a default value of latest cluster version on terraform side, and will update when API behavior fixed on cloud side.
