### ISSUE TITLE
ccev3: Empty attributes

### ISSUE THREAD

**Issue by vladimirBraquet** [terraform-providers/terraform-provider-flexibleengine#115]
### Terraform Version
`terraform -v
Terraform v0.11.7
`

### Affected Resource(s)
flexibleengine_cce_cluster_v3

### Terraform Configuration Files
```resource "flexibleengine_cce_cluster_v3" "backend" {
  name              = "backend"
  cluster_type      = "VirtualMachine"
  flavor_id         = "${var.cce_flavorId}"
  vpc_id            = "${var.vpcId}"
  subnet_id         = "${var.subnetId}"
  container_network_type  = "overlay_l2"
  cluster_version   = "v1.9.7-r1"
}
```

### Expected Behavior
Based on the [Flex Engine provider documentation](https://www.terraform.io/docs/providers/flexibleengine/r/cce_cluster_v3.html), the following attributes must be filled
- internal - The internal network address.
- external - The external network address.
- external_otc - The endpoint of the cluster to be accessed through API Gateway.

### Actual Behavior
The previous fields are empty, see the following state
```flexibleengine_cce_cluster_v3.backend:
  id = 757270cd-256a-11e9-86b8-0255ac101b11
  billing_mode = 0
  cluster_type = VirtualMachine
  cluster_version = v1.9.7-r1
  container_network_cidr = 172.16.0.0/16
  container_network_type = overlay_l2
  description =
  external =
  external_otc =
  flavor_id = cce.s1.large
  highway_subnet_id =
  internal =
  name = backend
  region = eu-west-0
  status = Available
  subnet_id = fe1cb32a-e998-4675-b3fe-5eb2c21c4434
  vpc_id = f828fc31-0207-4244-87ce-5c1973a14d53
```

**Comment by niuzhenguo** [comment]
@vladimirBraquet thanks for raising this, will clean up the 3 empty attributes, since API doesn't response with those informations.
