### ISSUE TITLE
AS Group : security group number is limited to only 1

### ISSUE THREAD

**Issue by vladimirBraquet** [terraform-providers/terraform-provider-flexibleengine#116]
### Terraform Version
```./terraform -v
Terraform v0.11.7
```
### Affected Resource(s)
flexibleengine_as_group_v1

### Terraform Configuration Files
```resource "flexibleengine_as_group_v1" "public_reverse_proxy" {
  scaling_group_name = "public_reverse_proxy"
  scaling_configuration_id = "${flexibleengine_as_configuration_v1.public_reverse_proxy.id}"
  desire_instance_number = 2
  min_instance_number = 0
  max_instance_number = 3
  networks          = [{id = "${flexibleengine_vpc_subnet_v1.subnet_internal.id}"}]
  security_groups   = [
    {id = "${flexibleengine_networking_secgroup_v2.public_reverse_proxy.id}"},
    {id = "${flexibleengine_networking_secgroup_v2.admin.id}"}
  ]
  vpc_id            = "${flexibleengine_vpc_v1.vpc.id}"
  lb_listener_id    = "${flexibleengine_elb_listener.listener_public_HTTP.id},${flexibleengine_elb_listener.listener_public_HTTPS.id}"
  delete_instances  = "yes"
}
```
### Expected Behavior
Creation of an AS group

### Actual Behavior
`{"error":{"code":"AS.2025","message":"The number of security groups in the AS group exceeds the upper limit."}}`
It seems that we can only use 1 Security group for AS group. However, the [documentation ](https://www.terraform.io/docs/providers/flexibleengine/r/as_group_v1.html#security_groups) says that "An array of one or more security group IDs to associate with the group"

**Comment by niuzhenguo** [comment]
@vladimirBraquet Seems the API behavior changed on cloud side, will dig more.

**Comment by niuzhenguo** [comment]
@vladimirBraquet Seems we can set only one security group on the console, I will update the docs on terraform side.
