### ISSUE TITLE
need to support binding EIP to a cluster with Terraform

### ISSUE THREAD

**Issue by WayneFromHuawei** [terraform-providers/terraform-provider-flexibleengine#118]
purpose of auto-provisioning as much as possible

one of the requires is to support binding EIP to a cluster with terraform, please help on it. thanks

**Comment by WayneFromHuawei** [comment]
@niuzhenguo  any updates?

**Comment by niuzhenguo** [comment]
@WayneFromHuawei just checked with the CCE team, there's no binding EIP API registered on API gateway now, need to do that first.

**Comment by antonin-a** [comment]
Hello guys, any update here ? CCE EIP attachment seems to be related to VPC service right ?

**Comment by niuzhenguo** [comment]
@antonin-a Yes, but CCE needs to expose the instance or port info which the VPC service need to bind the EIP address.

**Comment by niuzhenguo** [comment]
fixed by #269

**Comment by shoudusse** [comment]
Hello all,
Can you confirm me this new parameter is the same as setting a `clusterExternalIP` in `extend_param` ?
This was my workaround.

**Comment by niuzhenguo** [comment]
@shoudusse Yes, it's same with that.

**Comment by antonin-a** [comment]
Helllo @niuzhenguo , can we close this one ?

**Comment by niuzhenguo** [comment]
@antonin-a yes, closing it.
