### ISSUE TITLE
anti-affinity ECS Group when creating compute instance not implemented !!!

### ISSUE THREAD

**Issue by bbenduduh** [terraform-providers/terraform-provider-flexibleengine#133]
Hello

Unless I missed something, when creating compute instances via terraform, it is possible to specify an anti-affinity ECS Group for the instances. 

**Expected Behavior**
As spécified in the documentation for anti-affinity ECS Group : 

> ECSs in this group must be deployed on different hosts. 

**Actual Behavior**
The anti-affinity is not effective.  The ECS are launched on the same host.

`openstack server show frontend-01`
 OS-EXT-SRV-ATTR:host                 | pod2.eu-west-0a
 OS-EXT-SRV-ATTR:hypervisor_hostname  | nova007@3
 OS-EXT-SRV-ATTR:instance_name        | instance-000d75c8
 name                                 | frontend-01
 hostId                               | **551ec59027d385c0183b11673467ae71dcf0394dc061d854c4cbd64d**
 id                                   | f1bcc1ea-ca2d-4704-8229-b87d495dfb28

`openstack server show frontend-02`
 OS-EXT-SRV-ATTR:host                 | pod2.eu-west-0a
 OS-EXT-SRV-ATTR:hypervisor_hostname  | nova007@9
 OS-EXT-SRV-ATTR:instance_name        | instance-000d75c9
 name                                 | frontend-02
 hostId                               | **551ec59027d385c0183b11673467ae71dcf0394dc061d854c4cbd64d** (the Host )
 id                                   | 90432777-e814-45b0-a3c7-bd1fee0aaa44 (the instance created)

**Terraform Version**

$ terraform -v
Terraform v0.11.11
+ provider.flexibleengine v1.4.0

**Affected Resource(s)**

flexibleengine_compute_servergroup_v2",
flexibleengine_compute_instance_v2

**Steps to Reproduce**

Create an anti-affinity ECS Group via Terraform,
```
resource "flexibleengine_compute_servergroup_v2" "ecs_frontend_Group" {
  name     = "ecs_frontend_Group"
  policies = ["anti-affinity"]
}
```

Create two ECS with this anti-affinity ECS Group name.
```
resource "flexibleengine_compute_instance_v2" "frontend" {
  count           = "2"
  ........
  scheduler_hints {
    group = "${flexibleengine_compute_servergroup_v2.ecs_frontend_Group.id}"
  }
  ........
}
```

Thanks !

**Comment by niuzhenguo** [comment]
@bbenduduh Seems there's a race condition, terraform `count` will trigger multi resource creating concurrently. As the scripts above, two instance schedule at the same time, both suppose each other not in the anti-affinity group specified, can you please try to create one instance with the server group and then create another instance with that group to see? I will dig more to see how to solve such scenario.

**Comment by niuzhenguo** [comment]
@bbenduduh I checked with the ECS team and as there is a cascading layer upon each OpenStack pod, the hostId you see indicates a Pod instead of the real host. Please refer to the `OS-EXT-SRV-ATTR:hypervisor_hostname` which is the compute hostname. Sorry for the inconvenience.

**Comment by bbenduduh** [comment]
@niuzhenguo  
I rearragnged my Terraform script. With the right scenario: which means **without** using the parameter count!
One ECS each time, with the anti-affinity group.

Results: Same, the ECS are, again, launched on the same host. 
And the OS-EXT-SRV-ATTR:hypervisor_hostname  is same too !

| OS-EXT-SRV-ATTR:hypervisor_hostname  | **nova007@3**
| OS-EXT-SRV-ATTR:instance_name        | instance-000d7d28
| created                              | 2019-03-05T09:52:42Z
| name                                 | backend-za-01
| hostId                               | 551ec59027d385c0183b11673467ae71dcf0394dc061d854c4cbd64d

| OS-EXT-SRV-ATTR:hypervisor_hostname  | **nova007@3**
| OS-EXT-SRV-ATTR:instance_name        | instance-000d7d7f
| created                              | 2019-03-05T10:31:16Z
| name                                 | backend-za-02
| hostId                               | 551ec59027d385c0183b11673467ae71dcf0394dc061d854c4cbd64d

**Comment by niuzhenguo** [comment]
@bbenduduh Sorry for the misleading about `hypervisor_hostname`. Due to the cascading OpenStack layer, common users can't get the real host info of the instance they created through OpenStack CLI or API and they don't intend to expose such sensitive info to users. You just need to check whether the instances included in the anti-affinity server group members, if so, they are located on different hosts on the backend.

**Comment by bbenduduh** [comment]
@niuzhenguo

Ok, for the answer, and for such sensitive info !
On the other hand, I can not check if the anti-affinity is really taken into account.
Could you indicate the way to proceed please ?

**Comment by niuzhenguo** [comment]
@bbenduduh I'm sorry that we don't have a way to check anti-affinity if the host info not exposed on  cloud side, just like you can't check that on GUI as well.

**Comment by niuzhenguo** [comment]
Closing this, please feel free to reopen it if there's further questions, thanks!
