### ISSUE TITLE
EIP Binding on ECS is not working

### ISSUE THREAD

**Issue by Poil** [terraform-providers/terraform-provider-flexibleengine#136]
Hi there,

Not sure if I'm doing something wrong but actually my terraform plan does not bind the EIP on my network interface. If I run terraform a 2nd attempt it detect no change, if I bind manually my EIP, terraform detect no change.

### Terraform Version
```
Terraform v0.11.13
+ provider.flexibleengine v1.4.0
```

### Affected Resource(s)
- flexibleengine_vpc_eip_v1

### Terraform Configuration Files
```hcl
resource "flexibleengine_vpc_eip_v1" "eip_bastion" {
  publicip {
    type = "5_bgp"
    port_id = "${flexibleengine_compute_instance_v2.ecs_bastion.network.0.port}"
  }
  bandwidth {
    name = "bastion"
    size = 1
    share_type = "PER"
    charge_mode = "traffic"
  }
}
```

Anyone have experience with this ?

Best regards,

**Comment by Poil** [comment]
Sorry. was sleeping when reading the docs :x

**Comment by antonin-a** [comment]
No problem, coffee can probably fix it :) 
By the way, we plan to work on Flexible Engine modules so it will be easier for users to find working templates/examples and avoid that can of misunderstanding.
