### ISSUE TITLE
Retreiving data makes Terraform crash with AK/SK authentication method

### ISSUE THREAD

**Issue by osaluden** [terraform-providers/terraform-provider-flexibleengine#138]
Hi there,

### Terraform Version
```shell
$ terraform -v
Terraform v0.11.13
+ provider.flexibleengine v1.4.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- data flexibleengine_vpc_v1

### Terraform Configuration Files
main.tf
```hcl
data "flexibleengine_vpc_v1" "vpc" {
  name = "vpc-main"
}
```
provider.tf
```hcl
provider "flexibleengine" {
  insecure = true
  access_key = "XXXXXXXXXXX"
  secret_key = "YYYYYYYYYYYYY"
  auth_url   = "https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3"
  region     = "eu-west-0"
}
```

### Panic Output
https://gist.github.com/osaluden/d282d520cc84eea7f03cc837437fee5f 

### Expected Behavior
Terraform plan should display the VPC ID if the VPC with name "vpc-main"

### Actual Behavior
Terraform crashes at "plan" step

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Important Factoids
- Terraform does not crashes if run it with Openstack user_name/password/tenant_id/domain_id method.
- With AK/SK authentication methed, Terraform crashes only with "data" resources.
- Other accounts within the same FE tenant does not crashes with AK/SK method.
- I generated a new  AK/SK pair, same issue

**Comment by niuzhenguo** [comment]
@osaluden Please specify tenant_name/tenant_id as well when using AK/SK to avoid that issue.

**Comment by niuzhenguo** [comment]
@osaluden Can you please help to confirm if that solves you issue? then we can close this.

**Comment by vlandemaine-orange** [comment]
@niuzhenguo I tested with tenant_name/tenant_id and the same error occured.

**Comment by niuzhenguo** [comment]
@osaluden @vlandemaine-orange I can reproduce the issue with the scripts pasted above, but after adding tenant_name with the provider configuration, it works.
```
provider "flexibleengine" {
  insecure = true
  access_key = "XXXXXXXXXXX"
  secret_key = "YYYYYYYYYYYYY"
  auth_url   = "https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3"
  region     = "eu-west-0"
  tenant_name = "eu-west-0"
}
```

**Comment by osaluden** [comment]
Hello

Sorry for the late notice. I just checked with then tenant_name in addition, it works. 
Could it be possible to update the provider configuration documention ? https://www.terraform.io/docs/providers/flexibleengine/index.html

Another idea: since tenant_id = region_id, could it be possible to make the provider working without providing tenant_id ? (only region, access_key, secret_key and auth_url)

Thank you for your help

**Comment by antonin-a** [comment]
Hello Olivier, using Multi-Project feature (under IAM service) we can now create multi projects (tenant) on regions under Domains. 
So solution could be the opposite, working only with tenant_id and without region_id.

**Comment by osaluden** [comment]
OK I'm fine with your proposal

**Comment by niuzhenguo** [comment]
@antonin-a @osaluden Thanks for the proposal, will dig more and work on that later.
