### ISSUE TITLE
Provisioner file copy is not working, throwing connection error

### ISSUE THREAD

**Issue by dharmjit** [terraform-providers/terraform-provider-flexibleengine#144]
### Terraform Version
Terraform v0.11.8
+ provider.flexibleengine v1.4.0
+ provider.template v2.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- provisioner copy file

### Terraform Configuration Files
```
resource "flexibleengine_compute_instance_v2" "optisam_bastion_proxy" {
  name = "${var.platform_server_prefix}_optisam_bastion_proxy"
  some more lines

  provisioner "file" {
    source      = "yum.repo"
    destination = "/etc/yum.repos.d"

    connection {
      type        = "ssh"
      user        = "user"
      private_key = "${file("~/.ssh/key.pem")}"
    }
  }
}
```

### Debug Output
Dial tcp :22: connectex: No connection could be
made because the target machine actively refused it.

**Comment by niuzhenguo** [comment]
@dharmjit Are you executing Terraform on the same network as the new instance? Also can you show the `some more lines` on the script above?

**Comment by niuzhenguo** [comment]
@dharmjit do you still face the error?

**Comment by dharmjit** [comment]
Hi @niuzhenguo, I haven't tested again but will update this issue by checking again.

**Comment by niuzhenguo** [comment]
Closing this, please feel free to reopen it if the issue still exists.
