### ISSUE TITLE
ECS auto recovery

### ISSUE THREAD

**Issue by Gwenael22** [terraform-providers/terraform-provider-flexibleengine#162]
Hello,

When i use the flexible engine provider, my ECS servers are provisioned with disabled auto-recovery.
Is there a way to configure this properties when creating an ECS with the terraform providers ?

The API exposes the "extendparam/support_auto_recovery" to do that.

Thanks for your help.

**Comment by niuzhenguo** [comment]
@Gwenael22 Thank you for raising this. I will be working on that to make it available in the next release.

**Comment by Gwenael22** [comment]
Thanks @niuzhenguo
