### ISSUE TITLE
Feature request : Elastic Volume Storage data source request

### ISSUE THREAD

**Issue by julienyvenat** [terraform-providers/terraform-provider-flexibleengine#178]
Hello,

**Feature request:**
There is no data source function available to querying details about a single EVS Disk. This function will be helpful to attach a volume with the function `flexibleengine_compute_volume_attach_v2` without the need of create one. 

Today, we can't because the only way to get a `volume_id` for the function `flexibleengine_compute_volume_attach_v2` is to create a volume with the `flexibleengine_blockstorage_volume_v2` function.

It would be great to adding the data block type to the `flexibleengine_blockstorage_volume_v2` function.
The details about the API request are available for consultation here : https://docs.prod-cloud-ocb.orange-business.com/en-us/doc/pdf/20190321/20190321100742_49a1f8388a.pdf 
Reference : 8.x
Seems like nearly every API request in 6.x are deprecated.

**Use Case:**
A shared disk has been already created on Flexible Engine with data on it and we want to share this disk between multiple compute instance.

Thanks a lot !

**PS:**
If nobody had time to spend on this feature, I will look at it as I need this.

**Comment by niuzhenguo** [comment]
@julienyvenat Thanks for raising this, and I would appreciate if you can help work on this.

**Comment by julienyvenat** [comment]
Hey ! 

After some digging on the [Huawei Cloud golansdk](https://github.com/huaweicloud/golangsdk) repository, it appears that the `flexibleengine_blockstorage_volume_v2` wasn't what I needed. Like said in the title, I want to create an EVS (Elastic Volume Storage) and no function has been write on this plugin to get/create/delete ones. 

I found the go source code which manage evs for huawei cloud on so flexible engine I suppose : https://github.com/huaweicloud/golangsdk/tree/master/openstack/evs/v2/tags

I will work on the creation of the data and resource block type to manage evs.
Sorry for the misunderstanding on the previous post.

**PS:** 
I will not work for now on the addition of a data block type for `flexibleengine_blockstorage_volume_v2`.

**Comment by julienyvenat** [comment]
Hi @niuzhenguo ,

Sorry for this question where the answer must be somewhere but I don't find it :( .
I don't understand how to test the new build of the provider.
When I launch `terraform plan` an error saying that it didn't find the new function is raised :
`Error: data.flexibleengine_blockstorage_volume_v2.test_evs: Provider doesn't support data source: flexibleengine_blockstorage_volume_v2`.

And when I launch `make test`, it didn't find a test file and I don't know how to make one:
`?       github.com/terraform-providers/terraform-provider-flexibleengine        [no test files]`

Thank you for your answer and help !

**Comment by niuzhenguo** [comment]
@julienyvenat Sorry for the late response, you should add the new data source to provider.go file here https://github.com/terraform-providers/terraform-provider-flexibleengine/blob/master/flexibleengine/provider.go#L158-L191

**Comment by niuzhenguo** [comment]
@julienyvenat Are you still working on this? If not, I will add a PR for it.

**Comment by julienyvenat** [comment]
I'm not working on it for now.

**Comment by niuzhenguo** [comment]
@julienyvenat OK, I already created a PR and blockstorage_volume data source will be available on the next release. Sorry for the delay.

**Comment by julienyvenat** [comment]
@niuzhenguo No problem, thank you very much for your help and work.
