### ISSUE TITLE
CCE : "cluster_version" field and service pack

### ISSUE THREAD

**Issue by Gwenael22** [terraform-providers/terraform-provider-flexibleengine#179]
Hello,
I have some problem on CCE cluster provisioning concerning the field "cluster_version".
I use the version "v1.11.3-r1". After provisioning, FE change the version to "v1.11.3-r1.sp1".
If I want to modify a part of my stack, Terraform destroy my CCE cluster and create a new one because it identifies it is necessary to create a new resource.
Is there a way to fix this problem on provider source code or is it a problem on API ?
Thanks

**Comment by shoudusse** [comment]
I'm experiencing the same issue.
Obviously it's not a terraform provider issue but Flexible Engine API one.
If we create a CCE cluster with version "v1.11.3" the POST response returns a payload with
```
spec {
  "version": "v1.11.3-r1.sp1"
...
}
```

**Comment by Gwenael22** [comment]
Thanks @shoudusse

**Comment by antonin-a** [comment]
Hello @Gwenael22 & @shoudusse , have you opened a ticket on Flexible Engine platform service desk  ?

**Comment by Gwenael22** [comment]
Hello @antonin-a , not for the moment.

**Comment by Gwenael22** [comment]
Hello @antonin-a and @niuzhenguo
Response of Flexible Engine support : 

> Hello ,
> The provider should match the prefix of the CCE version but not the whole of the version string
> Because after every CCE upgrade, the version will be change but the prefix remains.
> when the response version is `v1.11.3-r1.sp1`, the terraform provider should treat it as `v1.11.3-r1`
> best regards

**Comment by niuzhenguo** [comment]
@Gwenael22 That's because the API response with v1.11.3-r1.sp1.

**Comment by niuzhenguo** [comment]
OK, we can truncate the version string on our side.

**Comment by Gwenael22** [comment]
Hello @niuzhenguo,
I don't know the technical constraints on API side but, i agree with you, it would be a better way to fix it in API. In fact, they have the control on the version naming and in case of name convention change on their side (for service pack version or example), the Terraform provider will not take it into account.
I don't have any contact with API developers but i can answer to FE support that it is perhaps a better way to fix it in API.

**Comment by niuzhenguo** [comment]
@Gwenael22 That would be great!

**Comment by Gwenael22** [comment]
the problem have been corrected. i suppose that it is on API side ...
