### ISSUE TITLE
Feature Request: Adding count to resource block for flexibleengine_csbs_backup_policy_v1

### ISSUE THREAD

**Issue by chewdevs** [terraform-providers/terraform-provider-flexibleengine#182]
Hi there,

It could be great to have a way to use count in the `ressource` block for `flexibleengine_csbs_backup_policy_v1` resource. 

For now, when using count for `flexibleengine_compute_instance_v2` resource, we need to use the count into the `flexibleengine_csbs_backup_policy_v1`. This is creating the same number of backups policies as the number of instances and not only one policy for all instances. 

Being able to use count into the `resource` block could be a way to resolve this.

### Terraform Version
```
terraform -v 
Terraform v0.11.11
+ provider.flexibleengine v1.5.0
+ provider.null v2.1.2
+ provider.openstack v1.18.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_csbs_backup_policy_v1

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
   resource "flexibleengine_csbs_backup_policy_v1" "backup_policy_k8s_node" {
   name  = "backup-${flexibleengine_compute_instance_v2.k8s_node.*.name[count.index]}"
   count = "${ var.enable_backup ? var.number_of_k8s_nodes : 0 }"
   resource {
     id = "${flexibleengine_compute_instance_v2.k8s_node.*.id[count.index]}"
     type = "OS::Nova::Server"
     name = "${flexibleengine_compute_instance_v2.k8s_node.*.name[count.index]}"
   }
   scheduled_operation {
     enabled = true
     operation_type = "backup"
     retention_duration_days = "14"
     trigger_pattern = "BEGIN:VEVENT\nRRULE:FREQ=DAILY;INTERVAL=1;BYHOUR=19;BYMINUTE=00\nEND:VEVENT"
   }
 }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by niuzhenguo** [comment]
@chewdevs I don't quite understand your request? `count` is provided by `terraform` for all resources, do you have some issue to use that?

**Comment by chewdevs** [comment]
If I tried to use `count` on the resource block inside the `flexibleengine_csbs_backup_policy_v1` resource using the code below, I got an error


```
  resource "flexibleengine_csbs_backup_policy_v1" "backup_policy_k8s_master" {
   name  = "backup-${flexibleengine_compute_instance_v2.k8s_master.*.name[count.index]}"
   resource {
     id = "${flexibleengine_compute_instance_v2.k8s_master.*.id[count.index]}"
     type = "OS::Nova::Server"
     name = "${flexibleengine_compute_instance_v2.k8s_master.*.name[count.index]}"
     count = "${ var.enable_backup ? var.number_of_k8s_masters : 0 }"
   }
   scheduled_operation {
     enabled = true
     operation_type = "backup"
     retention_duration_days = "14"
     trigger_pattern = "BEGIN:VEVENT\nRRULE:FREQ=DAILY;INTERVAL=1;BYHOUR=19;BYMINUTE=00\nEND:VEVENT"
   }

  lifecycle {
    prevent_destroy = true
    ignore_changes = ["scheduled_operation"]
  }
 }
```

Error message: 
```
terraform apply -var-file cluster.tf    ../../contrib/terraform/flexengine

Error: module.compute.flexibleengine_csbs_backup_policy_v1.backup_policy_k8s_master: resource.0: invalid or unknown key: count
```

**Comment by niuzhenguo** [comment]
@chewdevs Oh, I see, you mean a `count` parameter within resource block. Why not just move `count` outside resource?

**Comment by chewdevs** [comment]
This is what I have finally done but implies one policy per instance and not a global policy.

But I agree, with this solution, the problem is solved :smile:

**Comment by niuzhenguo** [comment]
@chewdevs If that's OK, can we close this?

**Comment by chewdevs** [comment]
Yes, we can
