### ISSUE TITLE
feature request : data source for flexibleengine_dns_zone_v2

### ISSUE THREAD

**Issue by Julien-Le-Huludut-Orange** [terraform-providers/terraform-provider-flexibleengine#184]
Hello

It would be nice to have a data source for dns zones : when you have multiple terraform deployments provisionning records in the same dns zone, you need the zone_id.

Thanks (in advance) !

**Comment by niuzhenguo** [comment]
@Julien-Le-Huludut-Orange Thanks for raising this, will include this in the v.16.0 milestone.
