### ISSUE TITLE
ECS SystemDisk Size parameter

### ISSUE THREAD

**Issue by jfpucheu** [terraform-providers/terraform-provider-flexibleengine#194]
Hello, 

By default the system_disk is set to 40 go . 
From the portal we can manage the size of this disk at the build.
IS it possible to do from terraform provider ? I did'nt found nothing in the documentation

Thanks

Jeff

**Comment by niuzhenguo** [comment]
@jfpucheu Please reference to https://www.terraform.io/docs/providers/flexibleengine/r/compute_instance_v2.html#boot-from-volume.
`boot_index = 0` within `block_device` indicates that it's a system disk.

**Comment by jfpucheu** [comment]
Thanks it work, maybe this information in the documentation should be great.
Jeff
