### ISSUE TITLE
 flexibleengine_compute_floatingip_v2

### ISSUE THREAD

**Issue by Poil** [terraform-providers/terraform-provider-flexibleengine#208]
Hi,

Here, https://github.com/terraform-providers/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_nat_snat_rule_v2_test.go, you create a floating ip via

```
resource "flexibleengine_networking_floatingip_v2" "fip_1" {
}
```

But in the documentation https://www.terraform.io/docs/providers/flexibleengine/r/compute_floatingip_v2.html, the pool is required.

Also I have to put the pool parameter or I have an error, but I'm unable to find which value I have to set on it, I don't find any "pool" configuration on FlexibleEngine

But on the API guide I don't find this required parameter https://docs.prod-cloud-ocb.orange-business.com/en-us/api/noa/en-us_topic_0057972991.html, or it's floating_network_id ?

*Edit*: Ok for me it's "admin_external_net" I found it via an API call

Best regards

**Comment by antonin-a** [comment]
Hello @Poil, you have to use the public network that can be found using the Openstack client command : "openstack network list --external" 

I will check the FE doc to try to find the reference and submit and Terraform provider documentation update. 

Regards,

**Comment by antonin-a** [comment]
Note that we are currently publishing modules on the Terraform registry, this one might help you: 
https://registry.terraform.io/modules/terraform-flexibleengine-modules/vpc/flexibleengine/1.0.1

**Comment by niuzhenguo** [comment]
I can add `admin_external_net` as a default value for pool parameter if you would like.

**Comment by antonin-a** [comment]
Hello @niuzhenguo , yes it is a good idea.
