### ISSUE TITLE
Example of load-balancer with TERMINATED_HTTPS configuration

### ISSUE THREAD

**Issue by lebrisg** [terraform-providers/terraform-provider-flexibleengine#215]
Hi,

On one of my project, I need to set up a load-balancer (flexibleengine_lb_loadbalancer_v2) with TERMINATED_HTTPS via Terraform.

I already had some problems to find an example of a load-balancer configuration using plain HTTP, but I finally found it.
But, concerning TERMINATED_HTTPS, I can't find any example and my project is stuck.
I currently get the following error message:
"* flexibleengine_lb_listener_v2.lb01_listener: Error creating listener: Bad request with: [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/lbaas/listeners], error message: {"NeutronError": {"message": "listener Create with PROTOCOL TERMINATED_HTTPS need certificate id", "type": "ListenerProtocolTERMINATEDHTTPSNeedCertID", "detail": ""}}"

If this feature is really available, it shouldn't be too difficult to provide an example.

**Comment by niuzhenguo** [comment]
@lebrisg Sorry for the inconvenience, will provide that soon.

**Comment by niuzhenguo** [comment]
@lebrisg Please refer to this https://github.com/terraform-providers/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_lb_listener_v2_test.go#L151-L221
