### ISSUE TITLE
datasource flexibleengine_cce_nodes_v3 should be plurial datasource

### ISSUE THREAD

**Issue by mgodlewski** [terraform-providers/terraform-provider-flexibleengine#221]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
$ terraform -v
Terraform v0.12.5
+ provider.flexibleengine v1.6.0
+ provider.template v2.1.2
```
### Affected Resource(s)
- datasource flexibleengine_cce_nodes_v3

### Terraform Configuration Files
```hcl
data "flexibleengine_cce_node_v3" "ccenodes_data" {
  count = "${var.cce_nodes_count}"
  cluster_id = "${flexibleengine_cce_cluster_v3.ccecluster.id}"
  depends_on = ["flexibleengine_cce_cluster_v3.ccecluster"]
}
```

### Debug Output
```
2019/08/02 14:10:13 [ERROR] module.cce: eval: *terraform.EvalReadData, err: Your query returned more than one result. Please try a more specific search criteria
...

Error: Your query returned more than one result. Please try a more specific search criteria

  on modules/cce/main.tf line 43, in data "flexibleengine_cce_node_v3" "ccenodes_data":
  43: data "flexibleengine_cce_node_v3" "ccenodes_data" {
```

### Expected Behavior
The datasource ends with a "s" which seems to be a [naming conventions for plurial datasources](https://www.terraform.io/docs/extend/best-practices/naming.html) (datasource returning a list).

### Actual Behavior
Having a list of data instead of error.

**Comment by niuzhenguo** [comment]
@mgodlewski the datasource `flexibleengine_cce_node_v3` itself doesn't end with a "s", I will change the docs instead.

**Comment by mgodlewski** [comment]
Great, you can keep this issue as a "feature request" : a plural datasource will be really helpfull to deal with cluster nodes.
