### ISSUE TITLE
Expected code for lb monitor always wrong.

### ISSUE THREAD

**Issue by lebrisg** [terraform-providers/terraform-provider-flexibleengine#232]
### Terraform Version
Terraform v0.11.8
+ provider.flexibleengine v1.6.0

### Affected Resource(s)
flexibleengine_lb_monitor_v2

### Terraform Configuration Files
resource "flexibleengine_lb_monitor_v2" "lb01_monitor" {
  pool_id         = "${flexibleengine_lb_pool_v2.lb01_pool.id}"
  type            = "HTTP"
  delay           = 20
  timeout         = 10
  max_retries     = 5
  url_path        = "/"
  expected_codes  = 200
  admin_state_up  = "true"
}

### Debug Output
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ flexibleengine_lb_monitor_v2.lb01_monitor
      expected_codes: "2xx" => "200"

Plan: 0 to add, 1 to change, 0 to destroy.

### Expected Behavior
Once the change is applied (expected_codes  = 200), they shouldn't be any new changes.

### Actual Behavior
"terraform apply" doesn't change anything, the same message (expected_codes: "2xx" => "200")
is always displayed, meaning a change is still needed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. set up a basic LB configuration with a LB monitor as previously shown
2. terraform plan
3. terraform apply
4. terraform plan

### Important Factoids
NA

### References
NA

**Comment by niuzhenguo** [comment]
@lebrisg Seems that's because the API resposne with 2xx instead.

**Comment by lebrisg** [comment]
I understand that I have to specify: expected_codes = "2xx"
Shouldn't be "200" or "200-202" as the Terraform documentation says?

**Comment by niuzhenguo** [comment]
@lebrisg I can ignore the API response and just keep the value you set.
