### ISSUE TITLE
facility 'data': access by login / password is no longer possible

### ISSUE THREAD

**Issue by bbenduduh** [terraform-providers/terraform-provider-flexibleengine#242]

**Comment by bbenduduh** [comment]
Hi,

After a while ... I realized that it was now necessary to use AK / SK.

There was no explicit error message! Is it a doc pb or a bug ?

### Terraform Version
Terraform v0.12.9
    provider.flexibleengine v1.7.0

### Affected Resource(s)
-

### Terraform Configuration Files
- provider.tf :
provider "flexibleengine" {
version = "= 1.7"
user_name = "${var.username}"
password = "${var.password}"
insecure = true
tenant_name = "${var.tenant_name}"
domain_name = "${var.domain_name}"
auth_url = "${var.endpoint}"
}

- data.tf
data "flexibleengine_networking_secgroup_v2" "secgroup"  { name = "sg_rds_db" }

### Panic Output
terraform crach !

### Expected Behavior
Terraform should not crach

### Actual Behavior
terraform crach !

### Steps to Reproduce
    terraform plan with simple 'get data'

**Comment by niuzhenguo** [comment]
@bbenduduh you need to provide the region information as well.

**Comment by bbenduduh** [comment]
It's ok  with region parameter added.
