### ISSUE TITLE
Applying  flexibleengine_rds_instance_v3 resource without changes recreate the database

### ISSUE THREAD

**Issue by bbenduduh** [terraform-providers/terraform-provider-flexibleengine#243]
Hi there,

Applying  _flexibleengine_rds_instance_v3_ resource,  **without any  changes**,  recreates the database.

I think this behavior needs to be corrected. The database must not be systematically recreated.

### Terraform Version
Terraform v0.12.9
+ provider.flexibleengine v1.7.0

### Affected Resource(s)
- lexibleengine_rds_instance_v3

### Terraform Configuration Files
resource "flexibleengine_rds_instance_v3" "rds_project_db" {
  availability_zone = ["eu-west-0a", "eu-west-0b" ]
  db {
    password = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    type = "MySQL"
    version = "5.7.17"
    port = "zzzz"
  }

  name = "rds_projetc_db"
  security_group_id = "${data.flexibleengine_networking_secgroup_v2.secgroup.id}"
  subnet_id = "${data.flexibleengine_networking_network_v2.network.id}"
  vpc_id = "${data.flexibleengine_vpc_v1.vpc.id}"

  volume {
    type = "COMMON"
    size = 100
  }

  flavor = "rds.mysql.s1.large.ha"

  ha_replication_mode = "async"

  backup_strategy {
    start_time = "01:30-02:30"
    keep_days = 5
  }
}

### Debug Output
  flexibleengine_rds_instance_v3.rds_project_db must be **replaced**
...
      ~ db {
            password  = "xxxxxxxxxxxxxxxxxxx"
            port      = "zzzz"
            type      = "MySQL"
          ~ user_name = "root" -> (known after apply)
          ~ version   = "5.7" -> "5.7.17" **# forces replacement**

### Expected Behavior
The database should not be destroyed and re-created.

### Actual Behavior
The database is destroyed and recreated.

### Steps to Reproduce
1. `terraform apply`

**Comment by niuzhenguo** [comment]
@bbenduduh Please change the version to 5.7 instead, seems API response with 5.7 when you specify 5.7.17.

**Comment by bbenduduh** [comment]
**Yes,** the database is not recreated if I specify the version at **5.7** instead of **5.7.17**

But if I do that, I have another pb. The database is created with the **latest** supported DB engine version, which is now 5.7.25.

That's not what I want.
For compatibility reasons  I would like the database DB engine to be  version 5.7.17

It would be great, if it were possible to specify the desired DB engine version by adding an appropriate argument.
