### ISSUE TITLE
VM m2.4xlarge.2 provisioning issue

### ISSUE THREAD

**Issue by bishoy-mgfs** [terraform-providers/terraform-provider-flexibleengine#254]
Hi there,

We are facing strange issue related when using Terraform FlexibleEngine provider.
When trying to creating a VM from different flavors, It success in some and fails in some Ex: Fail when creating m2 flavors.

### Terraform Version
Terraform v0.12.9

### Affected Resource(s)
- flexibleengine_compute_instance_v2

### Terraform Configuration Files
**instance.tf**

```
"dynamicVM" {
 name = var.name
 region            = var.region
 availability_zone = var.availability_zone
 flavor_id = var.flavor_id
 image_id  = var.image_id
 key_pair        = var.key_pair
 security_groups = [var.security_groups]
 network {
   uuid        = var.network_uuid
   fixed_ip_v4 = var.network_fixed_ip_v4
 }
 block_device {
   uuid                  = var.image_id
   source_type           = "image"
   destination_type      = "volume"
   volume_size           = 40
   boot_index            = 0
   delete_on_termination = true
 }
 block_device {
   source_type           = "blank"
   destination_type      = "volume"
   volume_size           = var.volume_size
   volume_type           = var.volume_type
   boot_index            = 1
   delete_on_termination = true
 }
}
```

**provider.tf**

```
provider "flexibleengine" {
 user_name   = var.user_name
 password    = var.password
 domain_name = var.domain_name
 tenant_name = var.tenant_name
 region      = var.region
 auth_url    = var.auth_url
}
```
```
variable "user_name" {
}
variable "password" {
}
variable "domain_name" {
 default = "***********"
}
variable "tenant_name" {
 default = "eu-west-0"
}
variable "region" {
 default = "eu-west-0"
}
variable "auth_url" {
 default = "https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3"
}
/*
instace.tf variables
*/
variable "name" {
}
variable "availability_zone" {
}
variable "flavor_id" {
 default = "m2.4xlarge.8"
}
variable "image_id" {
 default = "b12e6a91-eeaf-4f01-843d-ae0cffbf9341"
}
variable "key_pair" {
}
variable "security_groups" {
 default = "**********"
}
variable "network_uuid" {
 default = "*****************************************"
}
variable "network_fixed_ip_v4" {
}
variable "volume_size" {
 default = "100"
}
variable "volume_type" {
 default = "SSD"
}
```

### Expected Behavior
What should have happened?
Creating a VM with m2.4xlarge.8 flavor

### Actual Behavior
What actually happened?
The terraform apply command result in this error:

> Error waiting for instance (d7af377f-6722-47a8-a095-b9689d7c1d04) to become ready: unexpected state 'ERROR', wanted target 'ACTIVE'. last error: %!s(<nil>)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply -auto-approve -var 'user_name=*******' -var 'password=*****' -var 'name=aaa_test' -var 'availability_zone=eu-west-0b' -var 'key_pair=******' -var 'network_fixed_ip_v4=x.x.x.x'
`

**Comment by antonin-a** [comment]
Hello @DafuSHI , do you have any clue here ? My first guess would be a capacity issue but error message would be more explicit

**Comment by niuzhenguo** [comment]
We need to get the detailed error message from DEBUG log due to API didn't return any error.

**Comment by niuzhenguo** [comment]
hi, we will prepare a patch to give more explicit err mesage in such situation.

**Comment by niuzhenguo** [comment]
@ShiChangKuo ^

**Comment by ShiChangkuo** [comment]
@bishoy-mgfs @niuzhenguo 
we can get the error message in fault field of querying response body. 
The log message likes this:
Error: Error waiting for instance (_instance_id_) to become ready: [error code: 500, message: Build of instance _instance_id_ aborted: Block Device Mapping is Invalid.]
