### ISSUE TITLE
Manage identity ressource using FE provider

### ISSUE THREAD

**Issue by antonin-a** [terraform-providers/terraform-provider-flexibleengine#256]
Hi there,
It would be nice to have the possibility to handle identity ressource (IAM) with the terraform provider: 
As on Openstack provider : https://www.terraform.io/docs/providers/openstack/r/identity_application_credential_v3.html 
@niuzhenguo did you know if it is already available on Huawei side ?

**Comment by niuzhenguo** [comment]
@antonin-a It's also not supported on Huawei provider yet, and not sure if it's supported on Cloud side yet.

**Comment by antonin-a** [comment]
closing this one as it duplicate #214

**Comment by antonin-a** [comment]
closing this one as it duplicate #214
