### ISSUE TITLE
RDS instantiation flavors wrongly documented

### ISSUE THREAD

**Issue by Mihai-CMM** [terraform-providers/terraform-provider-flexibleengine#263]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
[root@localhost az_a]# terraform11.8 --version
Terraform v0.11.8
+ provider.flexibleengine v1.8.0
+ provider.openstack v1.23.0

### Affected Resource(s)
Please list the resources as a list, for example:
- _rds_instance_v3

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "flexibleengine_rds_instance_v3" "uip" {
  availability_zone = ["eu-west-0b", "eu-west-0b"]
  db {
    password = "UipXXXXX"
    type = "SQLServer"
    version = "2014 EE" ### THIS IS THE PROBLEM PER DOCUMENTATION
    port = "1433"
  }
-------
  }

### Debug Output
Error creating RdsInstanceV3, err=Error running api(create), err=Bad request with: [POST https://rds.eu-west-0.prod-cloud-ocb.orange-business.com/v3/8d2e5083fc8946a6aca19324d9527779/instances], error message: {"error_msg":"The DB engine does not exist.","error_code":"DBS.280269"}
### Solution - properly document the MSSQL engine types in the above case the "version" should be 2014_EE

https://www.terraform.io/docs/providers/flexibleengine/r/rds_instance_v3.html

**Comment by antonin-a** [comment]
Hello @Mihai-CMM , thank a lot for raising this doc issue. I've fixed it here and waiting for merging: #264
