### ISSUE TITLE
[MRS] Add support of 2.0.1 Cluster version

### ISSUE THREAD

**Issue by antonin-a** [terraform-providers/terraform-provider-flexibleengine#273]
Hi there,

MRS is currently supporting 2.0.1 cluster version: ![image (9)](https://user-images.githubusercontent.com/17782936/68426709-fa147680-01a8-11ea-9173-c1733546fc99.png) 

While the provider documentation is only referring "MRS 1.3.0 and MRS 1.5.0" (https://www.terraform.io/docs/providers/flexibleengine/r/mrs_cluster_v1.html#cluster_version), I know that is it really hard to track the available versions (same topic for CCE, RDS, ...) as it is moving quickly, I will submit a Pull Request in order to update the doc. 

In the meantime, can you confirm that it is only a documentation issue and that user would be able to:
- not set this argument as it is optional and it will use the 'latest version' by default (2.0.1)
- set this argument to '2.0.1' event if it is not listed on the authorized values 

Thank you by advance.

Antonin

**Comment by niuzhenguo** [comment]
- not set this argument as it is optional and it will use the 'latest version' by default (2.0.1)
Yes, the latest version will be used by default as the API document said.
- set this argument to '2.0.1' event if it is not listed on the authorized values
Yes, you can set any version now, we don't have a validator as it's really hard to track the available versions as you said above.

**Comment by antonin-a** [comment]
Ok clear, thanks a lot ! I will submit the pull request asap

**Comment by antonin-a** [comment]
#301 https://github.com/terraform-providers/terraform-provider-flexibleengine/pull/301
