### ISSUE TITLE
[MRS] add support for Hybrid cluster

### ISSUE THREAD

**Issue by mirceabostan** [terraform-providers/terraform-provider-flexibleengine#275]
Hi there,
While the console offers the possibility to create an analysis cluster, streaming cluster and hybrid cluster as in the snapshot bellow
![HybridCluster](https://user-images.githubusercontent.com/5604530/68490520-c9d4e280-0251-11ea-8630-d33e8351731d.png)

the provider documentation (https://www.terraform.io/docs/providers/flexibleengine/r/mrs_cluster_v1.html#cluster_version) offers
the possibility to create only :
cluster_type - (Optional) Type of clusters 0: analysis cluster 1: streaming cluster The default value is 0.

Do you have any updates foreseen to have also the hybrid cluster available in the terraform plugin?

Thanks you in advance,
Marian

**Comment by WayneFromHuawei** [comment]
@niuzhenguo please add this to the release at end of Nov, thanks

**Comment by niuzhenguo** [comment]
@mirceabostan @WayneFromHuawei Please have a look at this https://docs.prod-cloud-ocb.orange-business.com/en-us/api/mrs/mrs_02_0028.html

**Comment by niuzhenguo** [comment]
Currently, hybrid clusters (available in MRS 2.0.0 or later) cannot be created using APIs.

**Comment by mirceabostan** [comment]
Do you have any road map on the availability of creation of hybrid clusters through APIs?

**Comment by niuzhenguo** [comment]
@antonin-a @DafuSHI ^

**Comment by antonin-a** [comment]
@niuzhenguo @mirceabostan We plan to deliver the APIs capability on FE by the end of Decembre. @niuzhenguo we will send you the APIs doc asap in order to synchonize the APIs and Terraform provider releases

**Comment by screwyy** [comment]
@antonin-a Do you have any news on this ?

**Comment by antonin-a** [comment]
Hello @screwyy @niuzhenguo , sorry for this long delay but the we faced a lot of twists and turns with this change. The change is now done on platform side, @niuzhenguo can you update the provider in order to manage hybrid clusters ?

**Comment by DafuSHI** [comment]
I checked again the doc, today the cluster_type can be only 0 or 1: https://www.terraform.io/docs/providers/flexibleengine/r/mrs_cluster_v1.html

While API is already capable of creating hybride cluster: 2

@niuzhenguo can we put this update in the version of 715?

**Comment by ShiChangkuo** [comment]
@antonin-a @DafuSHI , we encounter an issue when creating a hybrid cluster and may need your help.
Here is the error message:

```
Bad request with: POST https://mrs.eu-west-0.prod-cloud-ocb.orange-business.com/v1.1/{project_id}/run-job-flow,
error message: {
    "errorCode":"12000002",
    "message":"Mixed cluster must have master node, analysis core node and streaming core node."
}
```

After checking with the [API doc](https://docs.prod-cloud-ocb.orange-business.com/api/mrs/mrs_02_0028.html), I think the `core_node_num` parameter takes no effect on hybrid cluster (cluster_type=2) which requires both analysis core node and streaming core node.
