### ISSUE TITLE
[Feature request] data source for flexibleengine_lb_certificate_v2

### ISSUE THREAD

**Issue by J-Le-Huludut-Orange** [terraform-providers/terraform-provider-flexibleengine#277]
Hello

We have several web apps in the same project/tenant that need the same wildcard SSL certificate. Each web app is deployed with its own terraform code. It would be nice to have a data source to avoid putting the cert in each terraform deployment (easier to maintain, more secure).

Do you think it's possible ?

Thanks !

**Comment by niuzhenguo** [comment]
@J-Le-Huludut-Orange Yes, we have such an API on Cloud side, I will be working on this.

**Comment by J-Le-Huludut-Orange** [comment]
@niuzhenguo  Thank you for your work !
