### ISSUE TITLE
ELB Cipher Suite Support

### ISSUE THREAD

**Issue by DafuSHI** [terraform-providers/terraform-provider-flexibleengine#280]
Hello,

Now Flexible Engine has supported to create listern with cipher suite chooses. It is already available in API. Can you help to implement that on Teraform?

**Comment by ShiChangkuo** [comment]
@DafuSHI flexibleengine_elb_listener resource has supported 'ssl_ciphers' argument which can meet your need.
https://www.terraform.io/docs/providers/flexibleengine/r/elb_listener.html#ssl_ciphers

**Comment by antonin-a** [comment]
hello @ShiChangkuo, it's ok for Elb but not for Enhanced Load Balancer (Enhanced ELB) that a majority of our users are using : https://www.terraform.io/docs/providers/flexibleengine/r/lb_listener_v2.html 
Regards,

**Comment by ShiChangkuo** [comment]
@antonin-a  After refreshing the [website](https://docs.prod-cloud-ocb.orange-business.com/api/elb/en-us_topic_0096561483.html), I have found the additional cipher suite feature, and we'll synchronize it on Terraform.
