### ISSUE TITLE
[CCEv2] New feature node-pool force node recreation

### ISSUE THREAD

**Issue by vlandemaine-orange** [terraform-providers/terraform-provider-flexibleengine#285]
Hi there,

We are facing an issue on CCEv2 nodes resources. Coming from the new features "node-pool" delivered in the end of the last year, this feature is not taken in account with the Terraform provider. 

The following annotation is always setted :

"annotations": {
              "kubernetes.io/node-pool.id": "eu-west-0b#s3.large.2#EulerOS 2.5"
},

If we create a new node, without annotation this annotation will be added automaticaly. So, when we update our plan, Terraform said that the resource need to be recreated because annotation removed without any update about this parameters.

### Terraform Version
0.12.13

### Affected Resource(s)
flexibleengine_cce_node_v3

### Expected Behavior
An update on the CCEv2 nodes without recreation

### Actual Behavior
An update on the CCEv2 with recreate due to the annotations node-pool.id

### Steps to Reproduce
Create a plan for creating a CCEv2 cluster with node, apply it and test to replan updates.

Regards,

Valentin LANDEMAINE
OCB - Professional Services

**Comment by niuzhenguo** [comment]
we can get rid of this pool id from annotations to avoid such issue.

**Comment by niuzhenguo** [comment]
@ShiChangkuo Can you help with this ^?

**Comment by ShiChangkuo** [comment]
sure! I'd be happy to do it.
