### ISSUE TITLE
[CCE] Advanced Node Configuration 

### ISSUE THREAD

**Issue by osaluden** [terraform-providers/terraform-provider-flexibleengine#297]
Hi there,

We would like the provider to be able to set advanced CCE Node configuration like preInstall and postInstall script at least but also all the settings available in "Advanced ECS Settings" and "Advanced Kubernetes Settings" in the Felxible Engine Console.

Thanks in advanced fort your help

Olivier

**Comment by niuzhenguo** [comment]
@osaluden I can't find the relevant arguments on CCE API docs :(

**Comment by wdesplas** [comment]
@niuzhenguo
Please refer to : 
* https://docs.prod-cloud-ocb.orange-business.com/cce/doc/download/pdf/cce-usermanual2.pdf
* Page 38

**Comment by antonin-a** [comment]
@niuzhenguo the url you just linked is the "User Guide" (console usage). What we need here is the API dcoumentation (https://docs.prod-cloud-ocb.orange-business.com/en-us/api/cce/en-us_topic_0053608539.html) but unfortunately there no information related to "pre/post instalation scripts". @DafuSHI can you help us here ? Can you confirm that APIS are exposed ? Is there a new version of the API doc ?

**Comment by wdesplas** [comment]
@antonin-a , @niuzhenguo 

My bad, I have post a bad document:
* Table 4-55 Data structure of the extendParam field
** https://docs.prod-cloud-ocb.orange-business.com/cce/doc/download/pdf/cce-api2.pdf
** page 62 : **alpha.cce/preInstall**
** page 62 : **alpha.cce/postInstall**

Br,
Willy
