### ISSUE TITLE
Feature Request: Data source for AZ

### ISSUE THREAD

**Issue by lperrin-obs** [terraform-providers/terraform-provider-flexibleengine#307]
To retrieve the availability zones, we have to use the `openstack_compute_availability_zones_v2` and `openstack_blockstorage_availability_zones_v3` Data sources.

It could be great to have the same data sources for the Flexible Engine provider.

**Comment by niuzhenguo** [comment]
@lperrin-obs Thanks for raising this, will be included in the next release.
