### ISSUE TITLE
Feature request : Create RDS read replicas

### ISSUE THREAD

**Issue by mgodlewski** [terraform-providers/terraform-provider-flexibleengine#319]
### Affected Resource(s)
- flexibleengine_rds_instance_v1
- flexibleengine_rds_instance_v3

### Expected Behavior
Create a read replica of an existing RDS

### Important Factoids
Currently, flexibleengine_rds_instance_v1 export the attribute "type" having "master" or "readreplica" value

Nonetheless, I can't find argument to create a read replica.

The [API doc](https://docs.prod-cloud-ocb.orange-business.com/en-us/api/rds/rds_01_0002.html) references a "replica_of_id" in table 3. Could you expose this parameter ?

**Comment by ShiChangkuo** [comment]
@mgodlewski thanks for raising, I will expose the parameter asap.
