### ISSUE TITLE
[SFS] Feature request: Many access rules for one share

### ISSUE THREAD

**Issue by shoudusse** [terraform-providers/terraform-provider-flexibleengine#332]
Hello there,

Right now, we can't give access to an SFS from multiple VPC.
Only one access rule can be grant through the 3 parameters `access_to`, `access_type` and `access_level`

Would be nice for an SFS to be accessible from many VPC. (this feature is possible from the GUI)

Thanks for your help

**Comment by DafuSHI** [comment]
@niuzhenguo I check from API document it has related APIs. Can we improve this part?

**Comment by niuzhenguo** [comment]
@DafuSHI Sure.
