### ISSUE TITLE
Can't create COLD/GLACIER OBS bucket

### ISSUE THREAD

**Issue by mgodlewski** [terraform-providers/terraform-provider-flexibleengine#337]
### Terraform Version
Terraform v0.12.13

### Affected Resource(s)
- flexibleengine_obs_bucket 

### Terraform Configuration Files
```hcl
resource "flexibleengine_obs_bucket" "test" {
  bucket = "test"
  acl    = "private"
  storage_class = "COLD"
}
```

### Expected Behavior
Create a OBS bucket

### Actual Behavior
```
Error: Error creating bucket mpa-prp-mysqldump: InvalidDefaultStorageClass,
 Reason: The default storage class is invalid, it can only be STANDARD, STANDARD_IA or GLACIER.
```

### Steps to Reproduce
`terraform apply`

### Terraform Configuration Files
```hcl
resource "flexibleengine_obs_bucket" "test" {
  bucket = "test"
  acl    = "private"
  storage_class = "GLACIER"
}
```

### Expected Behavior
Create a OBS bucket

### Actual Behavior
Error: expected storage_class to be one of [STANDARD WARM COLD], got GLACIER

### Steps to Reproduce
`terraform validate`

**Comment by ShiChangkuo** [comment]
@mgodlewski the first error was raised by API/sdk side while the second error was raised by provider.
I will cancel the validation of `storage_class` in provider, so you can use "GLACIER" to create a bucket.
