### ISSUE TITLE
RDS user_name creation

### ISSUE THREAD

**Issue by vlandemaine-orange** [terraform-providers/terraform-provider-flexibleengine#342]
Hello, 

We currently facing an issue about an RDS creation with the user_name parameter in the DB Block. When you specify a user_name in the db block, we have this issue : 

> Error: "db.0.user_name": this field cannot be set
> 
>   on compute/rds/main.tf line 23, in resource "flexibleengine_rds_instance_v3" "instance":
>   23: resource "flexibleengine_rds_instance_v3" "instance" {

Created like this: 

> resource "flexibleengine_rds_instance_v3" "instance" {
> ...
>   db {
> ...
>     user_name = var.rds_username
>   }
> ...
> }

### Terraform Version
Terraform 0.12.16

### Affected Resource(s)
- flexibleengine_rds_instance_v3

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
Create a RDS database with an username specified in the configuration.

### Actual Behavior
Fail with error log that said we cannot set this parameter

**Comment by ShiChangkuo** [comment]
@vlandemaine-orange
the `user_name` is an attribute which computed by the provider, so we can not set it.
sorry for the misleading website document, will fix it soon.
