### ISSUE TITLE
Customer encountered issue when creating a two NIC ECS

### ISSUE THREAD

**Issue by DafuSHI** [terraform-providers/terraform-provider-flexibleengine#372]
I am currently deploying servers on Flexbile Engine using Terraform.
When I deploy an ECS with two network cards or I hard fix the IP addresses, my ECS deploys well with the right addresses but my .tfstate file shows the same IP address twice for both cards and this generates an error if I restart a schedule, it destroys my server to recreate it.
Configuration of the ECS deployment:
Once the ECS is deployed, on the console I have the two desired network cards:
However if I look at the terraform.tfstate file:
I have the same network address twice, with the same MAC and the same name and two different UUIDs (these two UUIDs correspond well to the UUIDs of my subnets), this is problematic because if I restart a schedule without having made any changes. modification is still detected and this destroys my server to recreate

**Comment by ShiChangkuo** [comment]
@DafuSHI, as we discussed before, the ECS nics were created by **flexibleengine_vpc_subnet_v1**, which will have the same network name, then the issue was triggered.
we can fixed it by PR #373.
