### ISSUE TITLE
Add support for Anti DDOS feature

### ISSUE THREAD

**Issue by gberche-orange** [terraform-providers/terraform-provider-flexibleengine#43]
It would be great to be able to drive the flexible engine [anti-ddos product](https://docs.prod-cloud-ocb.orange-business.com/en-us/antiddos_dld/index.html) through the provider. 

Relates to https://github.com/terraform-providers/terraform-provider-huaweicloud/issues/38

**Comment by niuzhenguo** [comment]
@gberche-orange Sorry for the late reply, it's available now https://github.com/terraform-providers/terraform-provider-flexibleengine/pull/66

**Comment by gberche-orange** [comment]
@niuzhenguo can you please clarify the meaning of the following fields in the resource that don't match the flexible engine UI below, nor the service documentation at https://docs.prod-cloud-ocb.orange-business.com/en-us/antiddos_dld/index.html ?

![image](https://user-images.githubusercontent.com/4748380/52229756-fc624100-28b5-11e9-8227-883bfbce3550.png)


> traffic_pos_id - (Required) The position ID of traffic. The value ranges from 1 to 9.
>
>http_request_pos_id - (Required) The position ID of number of HTTP requests. The value ranges from 1 to 15.
>
>cleaning_access_pos_id - (Required)The position ID of access limit during cleaning. The value ranges from 1 to 8.
>
>app_type_id - (Required) The application type ID.


https://www.terraform.io/docs/providers/flexibleengine/r/antiddos_v1.html

**Comment by niuzhenguo** [comment]
@gberche-orange These fields are all coming from the API docs here https://docs.prod-cloud-ocb.orange-business.com/en-us/api/antiddos/en-us_topic_0037365550.html , not sure why there's no detail description on the docs, but I think traffic_pos_id = "Maximum Service Traffic" on the GUI, and the value 1 to 9 means 10 Mbps, 30Mbps, ..., 300Mbps. Seems need somebody from Anti DDos team to give a clarification @WayneFromHuawei
