### ISSUE TITLE
The "ELB" module create a "classic" of LB and not an "Enhanced" type

### ISSUE THREAD

**Issue by But4ler** [terraform-providers/terraform-provider-flexibleengine#57]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```hcl
Terraform v0.11.9
+ provider.flexibleengine v1.2.0

Your version of Terraform is out of date! The latest version
is 0.11.10. You can update by downloading from www.terraform.io/downloads.html

```

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_elb_loadbalancer

### Terraform Configuration Files
```hcl
resource "flexibleengine_elb_loadbalancer" "elb_app_prp" {
  name = "elb_app_prp"
  type = "External"
  vpc_id         = "${data.flexibleengine_vpc_v1.vpc_tools_prp.id}"
  admin_state_up = 0
  bandwidth      = 300
#   vip_address    = "${flexibleengine_vpc_eip_v1.eip_app_prp.publicip.0.ip_address}"
}
```

### Debug Output
Verification in the FE HMI
![image](https://user-images.githubusercontent.com/15019378/47514809-8ba49500-d881-11e8-8fda-dea448cbd161.png)

### Expected Behavior
Creation of an "Enhanced" Elastic Load Balance

### Actual Behavior
The module creates a "classic type" ELB

### Steps to Reproduce
1. `terraform apply`

### References

**Comment by niuzhenguo** [comment]
@But4ler ELB here means Elastic Load Balancer(classic). If you want to create an "Enhanced" Elastic Load Balancer, please use flexible_lb_xx instead.

**Comment by Julien-Le-Huludut-Orange** [comment]
Hello

I confirm, this is a misunderstanding on the ressources names (which aren't very clear, by the way ;-) ).
This issue can be closed.

**Comment by niuzhenguo** [comment]
@Julien-Le-Huludut-Orange Yes, indeed :( Will try to find a way to make it more clear in the future resource version.
