### ISSUE TITLE
feature request: ability to specify the AZ of the standby node on RDS instances

### ISSUE THREAD

**Issue by Julien-Le-Huludut-Orange** [terraform-providers/terraform-provider-flexibleengine#65]
Hello

Unless I missed something, when creating a RDS instance via terraform, it is not possible to specify the Availability Zone of the stanby instance.
It is required to specify the availability zone of the RDS, but this applies to the master and standby instance, and they end up in the same AZ.

This makes this service not suitable for a production environment, as there's no HA if the ressource has been created with terraform.

### Terraform Version
$ terraform -v
Terraform v0.11.10
+ provider.flexibleengine v1.2.0

### Affected Resource(s)
flexibleengine_rds_instance_v1

It would be great to see this implemented. For now we use terraform for almost every other ressources but we deploy RDS manually.

Thanks !

**Comment by niuzhenguo** [comment]
@Julien-Le-Huludut-Orange Thanks for the proposal, but I couldn't find a parameter to specify az for standby instance. Will reach out to product team for more information.

**Comment by antonin-a** [comment]
Hello @niuzhenguo , any update on this one ?

**Comment by niuzhenguo** [comment]
@antonin-a Still wait for the update on Cloud side to expose such ability.

**Comment by antonin-a** [comment]
ok, I can help on this side.

**Comment by Gwenael22** [comment]
Hello,
For information, the Flexible Engine support suggests me to use the following parameters to deploy a RDS database in 2 AZ :
`availabilityzone = "eu-west-0a,eu-west-0b"`
But it does not work (API error: RDS.5027","externalMessage":"HA invalid available zone")

**Comment by niuzhenguo** [comment]
@Gwenael22 That kind of availabilityzone only valid for V3 API.

**Comment by Gwenael22** [comment]
Sad news as FE exposes only a V1 version for RDS service

**Comment by Gwenael22** [comment]
Thanks @niuzhenguo 
Do you know if the provider project have planned to migrate the  flexibleengine_rds_instance ressource to V3 api ?

**Comment by niuzhenguo** [comment]
@Gwenael22 Yes, just wait for the V3 API exposed on Cloud side. AFAIK, it's not available for now.

**Comment by Gwenael22** [comment]
For information @niuzhenguo , the V3 version of RDS service was deployed the 2019-02-01 on my FE Tenant (source : GET request on https://rds.eu-west-0.prod-cloud-ocb.orange-business.com/rds )

**Comment by niuzhenguo** [comment]
@Gwenael22 Do you have V3 API docs or have you ever try with that?

**Comment by Gwenael22** [comment]
Unfortunately, the documentation is not up to date. I have requested it to FE support.

**Comment by Gwenael22** [comment]
@niuzhenguo the new documentation (api v3) https://docs.prod-cloud-ocb.orange-business.com/en-us/doc/pdf/20190517/20190517160742_24700f9cce.pdf
